### ISSUE TITLE
how to change sectionTitleTextColor

### ISSUE THREAD

**Issue by suninno** [sangcomz/StickyTimeLine#23] opened 2019-12-31 02:40 UTC
can you tell me how to change sectionTitleTextColor?

**Comment by sangcomz** [comment] 2019-12-31 02:44
Try this!

in Xml
```
   <xyz.sangcomz.stickytimelineview.TimeLineRecyclerView
        android:id="@+id/recycler_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:sectionTitleTextColor="#ffffff" />
```

**Comment by suninno** [comment] 2019-12-31 02:53
Good! Thank you!

**Comment by sangcomz** [comment] 2019-12-31 03:19
If the problem is resolved, please close the issue. 😀

**Closed** 2020-09-06 08:55 UTC
